name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
version: 2.0.0-beta.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^1.1.1
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <1.0.0'


dev_dependencies:
  lint: ^2.0.0
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
