name: code analysis & formatting

on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - name: Linter
        run: melos analyze
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - name: Format
        run: melos format --output none --set-exit-if-changed